Djangoproject/Djangoproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('Webapp/', include('Webapp.urls')),
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
]

Djangoproject/Webapp/urls.py
from django.urls import path
from .views import search_view
from . import views

app_name = 'Webapp'
urlpatterns = [
    path('top/', views.top_page, name='top'),
    path('search_view/', views.search_view, name='search_view')
]

Djangoproject/Webapp/models.py
from django.db import models

Djangoproject/Djangoproject/views.py
from django.shortcuts import render, redirect, reverse
from django.views import View

class index(View):
    def get(self, request, *args, **kwargs):
        return redirect(reverse('Webapp:top'))
index = index.as_view()

Djangoproject/Webapp/views.py
from django.shortcuts import render
from django.views import View
from django.http import HttpResponse
from django.template import loader
import requests

class SampleView(View):
	def get(self, request, *args, **kwargs):
		return render(request, 'Webapp/top.html')
top_page = SampleView.as_view()

def search_view(request):
    search_endpoint = 'Azure Cognitive Searchのエンドポイント'
    api_key = 'Azure Cognitive SearchのAPIキー'
    index_name = '検索対象のインデックス名'
    search_text = '若い男と老婆が揉める'

    response = requests.get(
        f'{search_endpoint}/indexes/{index_name}/docs/search?api-version=2020-06-30&search={search_text}',
        headers={'Content-Type': 'application/json', 'api-key': api_key}
    )

    data = response.json()
    search_results = data.get('value', [])

    context = {}
    if search_results:
        first_result = search_results[0]
        context = {
            'book_author': first_result.get('BookAuthor', ''),
            'release_date': first_result.get('Release_Date', ''),
            'book_name': first_result.get('BookName', ''),
            'rating': first_result.get('Rating', ''),
            'book_genre': first_result.get('BookGenre', ''),
        }

    return render(request, 'Webapp/results.html', context)

Djangoproject/templates/Webapp/results.html
<!DOCTYPE html>

{% load static %}

<html lang="ja">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>results</title>
    <link rel="stylesheet" href="{% static 'css/results.css' %}">
</head>
<body>
    <div class="text1">最も有力な候補はこの作品です</div>
    <div class="results1">
        <p>著者: {{ book_author }}</p>
        <p>発売日: {{ release_date }}</p>
        <p>書籍名: {{ book_name }}</p>
        <p>評価: {{ rating }}</p>
        <p>ジャンル: {{ book_genre }}</p>
    </div>
    <div class="text2">その他の候補はこちら</div>
    <div class="results2"><p>結果2</p></div>
    <div class="results3"><p>結果3</p></div>
    <div class="results4"><p>結果4</p></div>

    <button onclick="history.back(-1);return false;"><img src="{% static 'css/return.png' %}"></button>

</body>
</html>

Djangoproject/templates/Webapp/top.html
<!DOCTYPE html>

{% load static %}

<html lang="ja">
<head>
    <meta charset="utf-8">
    <title>bookssearch</title>
    <link rel="stylesheet" href="{% static 'css/top.css' %}">
</head>
<body>
    <label for="searchform_flag" class="button updown"><img src="{% static 'css/magnifying glass.png' %}"></label>
    <input type="checkbox" id="searchform_flag" class="searchform_check">
    <div class="searchform_popup">
        <form method="post" action="{% url 'Webapp:search_view' %}">
            {% csrf_token %}
            <input type="text" value="" name="s">
            <input type="submit" value="検索">
        </form>
    </div>
</body>
</html>